name = "luo-yuying-academic-api"
main = "src/index.js"
compatibility_date = "2026-08-23"

[[routes]]
pattern = "luo-api.aiecnu.site"
custom_domain = true

[[d1_databases]]
binding = "DB"
database_name = "luo-yuying-academic-site"
database_id = "7ee6e5a7-4b1f-4370-bf59-4bc2407e208b"

[vars]
ALLOWED_ORIGIN = "https://bigwhitetofu.github.io"
